# Generated by Django 5.0.2 on 2024-04-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Score",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("score", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="WikiPage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100, unique=True)),
                ("surrounding_links", models.TextField()),
                ("surrounding_titles", models.TextField()),
                ("link", models.CharField(max_length=100)),
                ("categories", models.TextField()),
            ],
        ),
    ]
