# Generated by Django 5.0.2 on 2024-03-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WikiPage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("surrounding_links", models.TextField()),
                ("link", models.CharField(max_length=100)),
                ("categories", models.TextField()),
            ],
        ),
    ]
